language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t zarerastromox/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true zarerastromox/docker-react npm run test